package-lock.json
src/feature.js
src/manifest.json
src/privileged/prefs/api.js
src/privileged/prefs/schema.json

Bring in 4 new pref functions:
setIntPref
getIntPref
setBoolPref
getBoolPref 
Change some prefs depending on the branch

Fix #6, set prefs per cohort.

---

src/feature.js
src/manifest.json
src/privileged/notificationBar/api.js
src/privileged/trackers/api.js
src/privileged/trackers/framescript.js
src/privileged/trackers/schema.json

~I'm not certain if this is the right approach, lots of messages flying everywhere, so I figured I'd let this brew here for a moment before merging.~
Thanks to some reviewing from @bwinton!

Fixes #15, Notification if trackers are on page.

---

README.md
src/feature.js
src/studySetup.js

for #28: explain running variations

for #28: link from README into docs/DEV.md

---

src/feature.js

clean up: Use webcrypto instead of bringing in a SHA
fixes: #37

Cleanup hashing, using WebCrypto.

---

src/content.js
src/studySetup.js
test/functional/0-setup.js
test/functional/1-telemetry.js
test/functional/utils.js

This adds tests that ensure that we're sending the correct data at the
correct moments.
This test already caught a bug where TIME_TO_LOAD_EVENT_END_MS would
always be empty, because it was sent before it was populated (in the
"load" event handler).

Add tests for Telemetry

---

src/feature.js
src/tabs.js

remove num_js_exceptions from payload

---

src/privileged/trackers/EveryWindow.js

EveryWindow now check if the window is private before executing the callback. This stops the `trackersExist` event from ever firing on page in a private window, so when we check from `feature.js`  if there are trackers in order to send telemetry it always fails. 
fixes: #60

Ensure telemetry does not send on private windows

---

.eslintrc.js
src/content.js
src/feature.js
src/privileged/notificationBar/api.js
src/privileged/trackers/api.js
src/privileged/trackers/framescript.js
src/studySetup.js
src/tabs.js
test/functional/0-setup.js
test/functional/1-telemetry.js
test/functional/utils.js

We should also make sure we have Circle-CI or Travis-CI enabled so that linting and building is done per commit instead of needing to run it manually.

Auto fix all the ESLint errors and fix a few warnings

---

src/privileged/notificationBar/api.js
src/privileged/trackers/framescript.js

r? @bryanbell
Fixes: #12.
Fixes: #19.

Finalize look of the popup survey.

---

README.md
docs/TELEMETRY.md
docs/TESTPLAN.md

Fixes #31 
Fixes #62
Can you think of any extra information that would be beneficial for QA in order to test this?

Add extra documentation describing behaviour

---

src/feature.js

- Using `storage.local` for the user id instead of sync - since it was mentioned that the uuid should never leave the device.
- on one tab, if the user is refreshing a page, sees and ignores the popup, they will not see it again until they navigate (not a refresh) at least once. Then it may be showed again on the same url or a different one.
- if the user has 2 tabs with the same url, they each will maintain a separate refresh count and a separate `tabInfo.surveyShown`, but as soon as one is intereacted with, it will apply to both - neither will get the survey again.
- once the popup has been interacted with it will never show again on a page that shares the same etld hash.

Do not show survey again once it has been interacted with.

---

package.json

Edit package.json names

---

src/feature.js
src/privileged/trackers/api.js
src/privileged/trackers/schema.json
test/functional/3-add-exception.js

Should we add to the ping when a page has already been excepted?
Should we add to the ping when a user removes an exception?

Add to telemetry ping when user adds page as an exception.

---

docs/TELEMETRY.md
src/studySetup.js
src/tabs.js

I wanted to make a PR here just to double check with you that the time for this study is indeed 14 days?

Set expiry to 14 days.

---

docs/TELEMETRY.md
src/feature.js
src/privileged/trackers/api.js
src/privileged/trackers/framescript.js
src/tabs.js
test/functional/1-telemetry.js

Add some prefs to the telemetry payload.

---

src/manifest.json

add a description to the add-on.

---

test/functional/0-setup.js
test/functional/2-trackers.js

Enable disabled tracker tests!

---

src/feature.js
src/privileged/notificationBar/api.js
test/functional/5-reload-doorhanger.js

I'd like to add more tests for the doorhanger (this doesn't even cover the feature I'm adding), but I didn't have the time right now.

Record previous doorhanger states

---

src/background.js
src/feature.js
src/manifest.json
src/privileged/popupNotification/api.js
src/privileged/popupNotification/schema.json
src/studySetup.js
test/functional/1-telemetry.js
test/functional/2-trackers.js

Erica, can you give this a quick sanity check before I merge this into the branch for Nihanth?

Address review comments

---

src/feature.js

hash etld in reload handler

---

README.md
docs/TESTPLAN.md
src/variations.js
test/functional/0-setup.js

Add missing browser.safebrowsing.provider.mozilla.lists pref

---

src/privileged/trackers/framescript.js

From my testing, getting the document from the event target of the
unload event is more reliable than accessing the document getter on the
docShell. I'm not sure why the docShell loses this property earlier, but
it makes sense to use the event target since this is a web API and
should have more stability guarantees than our internal docShell.

Get the document from the unload event instead of the docShell

---

package-lock.json
package.json
src/manifest.json
src/studySetup.js

remove testing flag, increment version number
